# Generated by Django 4.2.1 on 2023-06-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomlistTrack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('artist', models.CharField(max_length=200, verbose_name='Artist')),
                ('lookupkey', models.TextField(max_length=400, verbose_name='Lookupkey')),
                ('includedon', models.DateTimeField(auto_now=True)),
                ('customlistid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customlists.customlist')),
            ],
        ),
    ]
