# Generated by Django 4.2.1 on 2023-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
